jobs:
  # android open video call  
  # - template: cicd/templates/build-android.yml
  #   parameters:
  #     displayName: 'AndroidOpenVideoCall'
  #     workingDirectory: 'Group-Video/OpenVideoCall-Android'

  # android 1 to 1 tutorial
  - template: cicd/templates/build-android.yml
    parameters:
      displayName: 'AndroidTutorial'
      workingDirectory: 'One-to-One-Video/Agora-Android-Tutorial-1to1'

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSSwiftTutorial'
      workingDirectory: 'One-to-One-Video/Agora-iOS-Tutorial-Swift-1to1'
      scheme: 'Agora iOS Tutorial'
  
  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSOCTutorial'
      workingDirectory: 'One-to-One-Video/Agora-iOS-Tutorial-Objective-C-1to1'
      scheme: 'Agora iOS Tutorial Objective-C'

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSSwiftOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-iOS'
      scheme: 'OpenVideoCall'

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSOCOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-iOS-Objective-C'
      scheme: 'OpenVideoCall'

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacSwiftTutorial'
      workingDirectory: 'One-to-One-Video/Agora-macOS-Tutorial-Swift-1to1'
      scheme: 'Agora Mac Tutorial Swift'

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacOCTutorial'
      workingDirectory: 'One-to-One-Video/Agora-macOS-Tutorial-Objective-C-1to1'
      scheme: 'Agora Mac Tutorial Objective-C'

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-macOS'
      scheme: 'OpenVideoCall'